name: ${project.artifactId}
version: ${project.version}
main: com.mcmiddleearth.mcmescripts.MCMEScripts
api-version: 1.16
authors: [ Eriol_Eandur ]
depend: [ MCME-Entities ]

commands:
  scripts:
    description: Manages scripts.
    permission: mcmescripts.user
    usage: /scripts debug | reload

permissions:
  mcmescripts.user:
    default: op
    description: Allows to import and export scripts.
  mcmescripts.admin:
    default: op
    children:
      mcmescripts.user: true
    description: Allows to enable and disable scripts and do debugging