name: ${project.artifactId}
version: ${project.version}
main: com.mcmiddleearth.mcmescripts.MCMEScripts
api-version: 1.16
authors: [ Eriol_Eandur ]
depend: [ MCME-Entities ]

commands:
  scripts:
    description: Manages scripts.
    permission: mcmescripts.admin
    usage: /scripts debug | reload

permissions:
  mcmescripts.admin:
    default: op
    description: Allows to manage scripts.